<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentBlockRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentBlockRepository extends EntityRepository
{
    public function findBySlugs($slugAry)
    {
        $query = $this->getEntityManager()->createQuery(
                'SELECT c FROM App:ContentBlock c WHERE c.slug IN (:slugAry)'
            );
        $query->setParameter('slugAry', $slugAry);

        return $query->getResult();
    }
}
