<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionRepository extends EntityRepository
{
}
