<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends EntityRepository
{
    public function findAllNonBatTaxa($batGroup)
    {
        return $this->createQueryBuilder('taxon')
            ->leftJoin('taxon.group', 'group_taxon')
            ->andWhere('group_taxon.group != :batGroup')
            ->setParameter('batGroup', $batGroup)
            ->getQuery()
            ->execute();
    }
}
