<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonymRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonymRepository extends EntityRepository
{
}
