imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   "%database_name%_test"
        server_version: 10.0.30

framework:
    profiler: { only_exceptions: true }
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true
