imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    publication_file_dir: '%kernel.project_dir%/web/uploads/publications'

framework:
    translator:
        fallbacks:
            - '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enable_annotations: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    templating:
        engines:
            - twig
    default_locale: '%locale%'
    session: null
    fragments: null
    http_method_override: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        fos_csrf_provider: '@security.csrf.token_manager'
    form_themes:
        - 'form/fields.html.twig'

doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            blameable: true
            timestampable: true
            sluggable: true
            softdeleteable: true

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: ssl
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: noreply@batbase.org
        sender_name: BatBase.org
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\RegistrationType
    profile:
        form:
            type: AppBundle\Form\ProfileType

webpack_encore:
    output_path: "%kernel.project_dir%/web/build"

mobile_detect:
    redirect:
        full:
            is_enabled: true            # default false
            # host: https://batbase.com       # with scheme (http|https), default null, url validate
            # status_code: 301            # default 302
            action: no_redirect           # redirect (default), no_redirect, redirect_without_path
        mobile:
            is_enabled: true            # default false
            # host: https://m.batbase.com     # with scheme (http|https), default null, url validate
            # status_code: 301            # default 302
            action: no_redirect            # redirect, no_redirect, redirect_without_path
        tablet:
            is_enabled: true            # default false
            # host: http://t.site.com     # with scheme (http|https), default null, url validate
            # status_code: 301            # default 302
            action: no_redirect            # redirect, no_redirect, redirect_without_path
        # detect_tablet_as_mobile: false   # default 
    switch_device_view:
        save_referer_path: true        # default true
                                        # true  redirectUrl = http://site.com/current/path?currentQuery=string
                                        # false redirectUrl = http://site.com
    service:
        mobile_detector: mobile_detect.mobile_detector.default
    cookie_key: "device_view"                     # default
    cookie_expire_datetime_modifier: "+1 month"   # default
    switch_param: "device_view"                   # default
    device_view_class: SunCat\MobileDetectBundle\Helper\DeviceView
    request_response_listener_class: SunCat\MobileDetectBundle\EventListener\RequestResponseListener
    twig_extension_class: SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension

ewz_recaptcha:
    public_key:  6LdbSaQZAAAAANXmfQ0OsqYUk9d01qlb6jh9Jjq5
    private_key: 6LdbSaQZAAAAAHhUv2zqzzL0YRrIAWzxkfen60li
    # enabled: true
    # ajax: false