security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/crud/, role: ROLE_EDITOR }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: profile/edit, roles: ROLE_USER }
        - { path: lists/edit, roles: ROLE_USER }
        - { path: /edit$, roles: ROLE_EDITOR }
        - { path: /update$, roles: ROLE_ADMIN }
        - { path: /delete$, roles: ROLE_ADMIN }
        - { path: /new$, roles: ROLE_ADMIN }
        - { path: feedback/post, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_BETA:        [ROLE_USER]
        ROLE_EDITOR:      [ROLE_USER, ROLE_BETA]
        ROLE_ADMIN:       [ROLE_USER, ROLE_BETA, ROLE_EDITOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_BETA, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
