<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InteractionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoJsonRepository extends EntityRepository
{
    public function findByLocation($locId)
    {
        return $this->createQueryBuilder('g')
            ->where('g.loc_id = :id')
            ->setParameter('id', $locId)
            ->getQuery() 
            ->getResult();
    }
}
